---
- name: Check for conjur registry access
  shell: |
    cat ~/.docker/config.json
  ignore_errors: yes
  register: conjurRegistry

- name: Check for conjur.tar
  stat:
     path: ../conjur.{{item}}
  with_items:
    - "tar"
    - "tar.gz"
    - "tgz"
  register: conjurTar

- name: Inform about Enterprise availability
  set_fact:
    conjur_version: 'EE'
  when: conjurTar.stat.exists == True

- name: Load Conjur tar
  docker_image:
    name: conjur-appliance
    load_path: item.stat.path
    state: present
    timeout: 120
    when: item.stat.exists == True
  with_items: conjurTar
  when: (conjurRegistry.stdout.find('registry2.itci.conjur.net') == -1) and (conjurTar.stat.exists == True)

- include_tasks: conjurCLI.yml

- include_tasks: conjurOSS.yml
  when: ((conjurTar.stat.exists == False and (conjurRegistry.stdout.find('registry2.itci.conjur.net') == -1)) or conjur_version == 'OSS')

- include_tasks: conjurEE.yml
  when: ((conjurRegistry.stdout.find('registry2.itci.conjur.net') != -1) or (conjurTar.stat.exists == True)) and conjur_version == 'EE'
